name: IMPACT production deploy

on: [push, workflow_dispatch]
  
permissions:
  id-token: write
  contents: read

env:
  location: polandcentral
  rg_name: impcat
  sa_name: impactuniquesa
  ai_name: impactinsight
  af_name: impactfunctionwithuniquename

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
    
  #   - uses: actions/checkout@v5
  
  #   - uses: actions/setup-dotnet@v5
  #     with:
  #       dotnet-version: '8.0.x'

  #   - run: dotnet build
  #     working-directory: Tenders

  deploy:
    runs-on: ubuntu-latest

    steps:
  
    - name: Login to Azure using OIDC
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.APP_CLIENT_ID }}
        tenant-id: ${{ secrets.TENANT_ID }}
        subscription-id: ${{ secrets.SUBS_ID }}

    - name: Deploy base infrastructure
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az group create --name ${{ env.rg_name }} --location ${{ env.location }}
          az storage account create --name ${{ env.sa_name }} --location ${{ env.location }} --resource-group ${{ env.rg_name }} --sku Standard_LRS
          az functionapp create --name ${{ env.af_name }} --resource-group ${{ env.rg_name }} --storage-account ${{ env.sa_name }} --consumption-plan-location ${{ env.location }}
          # az monitor app-insights component create --app ${{ env.ai_name }} --location ${{ env.location }} --resource-group ${{ env.rg_name }} --retention-time 30
          # az monitor app-insights component connect-function --resource-group ${{ env.rg_name }} --app ${{ env.ai_name }} --function ${{ env.af_name }}

    - run: sudo apt-get install azure-functions-core-tools-4
      name: TryInstall

    - run: func --version